twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        siteName: '%app.siteName%'
        siteDescription: '%app.siteDescription%'
        siteAlert: '%app.siteAlert%'

